GET http://localhost:8080/

###

GET http://localhost:8080/api/usuarios

###

POST http://localhost:8080/api/usuarios
Content-Type: application/json

{
    "email": "Iago@email.com",
    "senha": "hiagomais20"
}

###

POST http://localhost:8080/api/usuarios/login
Content-Type: application/json

{
    "email": "felipe@email.com",
    "senha": "felipe2020"
}

###

PUT http://localhost:8080/api/usuarios?id=1
Content-Type: application/json

{
    "email": "mariaaparecida@email.com",
    "senha": "123maria456"
}

###

DELETE http://localhost:8080/api/usuarios?id=5
