GET http://localhost:8080/

###

GET http://localhost:8080/alunos

###

POST http://localhost:8080/alunos
Content-Type: application/json

{
    "NOME": "Maria"
}

###

PUT http://localhost:8080/alunos?id=1261b8e9-b145-4127-a164-2f6bcb2de88f
Content-Type: application/json

{
    "nome": "Carlos da Silva"
}

###

DELETE http://localhost:8080/alunos?id=1261b8e9-b145-4127-a164-2f6bcb2de88f
